//
// Copyright (c) 2021-2023 suzumushi
//
// 2023-12-28		version.h
//
// Licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 (CC BY-NC-SA 4.0).
//
// https://creativecommons.org/licenses/by-nc-sa/4.0/
//

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"SoundObject.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"SoundObject VST3 (64Bit)"
#else
#define stringFileDescription	"SoundObject VST3"
#endif
#define stringCompanyName		"suzumushi\0"
#define stringLegalCopyright	"Copyright(c) 2021-2024 suzumushi."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
